name: Automate_Launching_System_001

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up Ruby
        uses: actions/setup-ruby@v2
        with:
            ruby-version: '3.x'
  
      - name: Run server.py
        run: python data/launch.py