name: update_data_001

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  import-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installez ici les dépendances nécessaires pour votre script
          # par exemple : pip install pandas

      - name: Run import script
        run: python /data/src/import_users.py